[package]
name = "contracts"
version = "1.2.0"
cairo-version = "2.7.0"

[dependencies]
starknet = "2.7.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.0" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.27.0" }


[[target.starknet-contract]]
casm = true

[tool.fmt]
sort-module-level-items = true